<?php
// @formatter:off
/** @var $this \app\models\core\View */
/** @var $_block \app\models\core\Chart\Bar */

$chartId = $id;
$chartVar = 'chart_' . $chartId;
?>

<div id="<?= $chartId ?>" class="chart <?= $class ?> <?= $type ?>">
    <div class="chart-heading">
        <h2 class="chart-title"><?= $this->__($title) ?></h2>
    </div>
    <div class="chart-body">
        <div class="toolbar">
            <form action="javascript:void(0)" id="<?= $chartId ?>_form">
                <ul>
                    <?php foreach ($filters as $filterElement): /* @var $filterElement \app\models\core\Form\Element\AbstractElement */ ?>
                        <li>
                            <span class="filter-label"><?= $this->__($filterElement->getLabel()) ?></span>
                            <div class="filter-input">
                                <?= $filterElement->toHtml() ?>
                            </div>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </form>
        </div>
        <?php if ($show_legend): ?>
            <div class="legend"></div>
        <?php endif; ?>

        <div class="canvas-container">
            <div class="loading-anim"></div>
            <canvas width="<?= $width ?>" height="<?= $height ?>"></canvas>
        </div>

        <script>
            //<![CDATA[
            window.addEventListener('DOMContentLoaded', function() {
                (function($) {
                    const chart = new Chart($('#<?= $chartId ?> canvas').get(0), {
                        type: 'bar',
                        options: {
                            animation: false,
                            responsive: true,
                            scaleBeginAtZero: true,
                            scales: {
                                x: {
                                    type: 'time',
                                },
                            },
                            plugins: {
                                tooltip: {
                                    enabled: true,
                                    usePointStyle: true,
                                    callbacks: {
                                        title: (data) => data[0].dataset.label,
                                        label: (data) => <?= $_block->getTooltipJsCallback('data.parsed.y') ?>,
                                    },
                                },
                            }
                        },
                    });

                    const updateChart = function() {
                        $('#<?= $chartId ?> .loading-anim').show();

                        const filters = $('#<?= $chartId ?>_form').serialize();
                        $.getJSON("<?= $data_url ?>", filters, function(data) {
                            $('#<?= $chartId ?> .loading-anim').hide();
                            $('#<?= $chartId ?> .no-data-message').remove();
                            if (data == null || !data.datasets?.length) {
                                if (typeof chart != "undefined") {
                                    chart.clear();
                                }
                                $('#<?= $chartId ?> canvas').after('<div class="no-data-message"><?= $this->__($no_data_message); ?></div>');
                                return;
                            }
                            whbChartjs.populateBarChartWithData(chart, data);
                        });
                    }

                    $(window).load(function() {
                        updateChart();
                        $('#<?= $chartId ?> .toolbar select').change(updateChart);
                    });
                })(jQuery);
            });
            //]]>
        </script>
        <div class="clear"></div>
        <?php if ($footer_note): ?>
            <div class="chart-footer right">
                <p><?= $footer_note ?></p>
            </div>
        <?php endif; ?>
    </div>
</div>
