<?php
/**
 * Created by PhpStorm.
 * User: anael
 * Date: 11/11/15
 * Time: 14:35
 */

$chartId = $id;
$chartVar = 'chart_' . $chartId . '_';
?>

<div id="<?php echo $chartId ?>" class="chart <?php echo $class ?> <?php echo $type ?>">
    <div class="chart-heading">
        <h2 class="chart-title"><?php echo $this->__($title) ?></h2>
    </div>
    <div class="chart-body">
        <div class="canvas-container">
            <canvas width="<?php echo $width ?>" height="<?php echo $height ?>"></canvas>
        </div>
        <div class="toolbar">
            <form action="javascript:void(0)" id="<?php echo $chartId ?>_form">
                <ul>
                    <?php foreach ($filters as $filterElement): /* @var $filterElement \app\models\core\Form\Element\AbstractElement */ ?>
                        <li>
                            <span class="filter-label"><?php echo $this->__($filterElement->getLabel()) ?></span>
                            <div class="filter-input">
                                <?php echo $filterElement->toHtml() ?>
                            </div>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </form>
        </div>
        <?php if ($show_legend): ?>
            <div class="legend"></div>
        <?php endif; ?>

        <script type="application/javascript">
            //<![CDATA[
            var <?php echo $chartVar ?>Canvas = new Chart($('#<?php echo $chartId ?> canvas').get(0).getContext('2d'));
            <?php echo $chartVar ?>Canvas = <?php echo $chartVar ?>Canvas.Doughnut({}, {
                animation: false,
                responsive: true,
                datasetFill : false,
                /*animateScale: true,*/
                legendTemplate : "<ul class=\"<%=name.toLowerCase()%>-legend\">"+
                    "<% for (var i=0; i<segments.length; i++){%>"+
                    "<li><span class=\"label-color\" style=\"background-color:<%=segments[i].fillColor%>\"></span><span class=\"label-text\"><%if(segments[i].label){%><%=segments[i].label%><%}%></span></li>"+
                    "<%}%></ul>",
                tooltipTemplate: "<%if (label){%><%=label%><%}%>"
            });

            function update<?php echo $chartVar ?>() {
                var filters = $('#<?php echo $chartId ?>_form').serialize();
                $.getJSON("<?php echo $data_url ?>", filters, function(data) {
                    $('#<?php echo $chartId ?> .no-data-message').remove();
                    while (<?php echo $chartVar ?>Canvas.segments.length) {
                        <?php echo $chartVar ?>Canvas.removeData();
                    };
                    $(data).each(function(idx, datapoint) {
                        <?php echo $chartVar ?>Canvas.addData(datapoint);
                    });
                    <?php echo $chartVar ?>Canvas.update();
                    $('#<?php echo $chartId ?> .legend').empty();
                    if (data.length > 0) {
                        $('#<?php echo $chartId ?> .legend').append(<?php echo $chartVar ?>Canvas.generateLegend());
                    }
                    else {
                        $('#<?php echo $chartId ?> canvas').after('<div class="no-data-message"><?php echo $this->__($no_data_message); ?></div>');
                    }
                });
            }

            $(window).load(function() {
                update<?php echo $chartVar ?>();
                $('#<?php echo $chartId ?> .toolbar .filter-input').change(update<?php echo $chartVar ?>);
            });
            //]]>
        </script>
        <?php if ($footer_note): ?>
            <div class="chart-footer right">
                <p><?php echo $footer_note ?></p>
            </div>
        <?php endif; ?>
    </div>
</div>