<?php
// @formatter:off
/** @var $_block \app\models\core\Chart\Line */

$chartId = $id;
$chartVar = 'chart_' . $chartId;
?>

<div id="<?= $chartId ?>" class="chart <?= $class ?> <?= $type ?>">
    <div class="chart-heading">
        <h2 class="chart-title"><?= $this->__($title) ?></h2>
    </div>
    <div class="chart-body">
        <div class="toolbar">
            <form action="javascript:void(0)" id="<?= $chartId ?>_form">
                <ul>
                    <?php foreach ($filters as $filterElement): /* @var $filterElement \app\models\core\Form\Element\AbstractElement */ ?>
                        <li>
                            <span class="filter-label"><?= $this->__($filterElement->getLabel()) ?></span>
                            <div class="filter-input">
                                <?= $filterElement->toHtml() ?>
                            </div>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </form>
        </div>
        <?php if ($show_legend): ?>
            <div id="<?= $chartId ?>-legend-container" class="legend"></div>
        <?php endif; ?>

        <div class="canvas-container">
            <canvas width="<?= $width ?>" height="<?= $height ?>"></canvas>
        </div>

        <script>
            window.addEventListener('DOMContentLoaded', function() {
                (function($) {
                    //<![CDATA[
                    const chart = new Chart($('#<?= $chartId ?> canvas').get(0), {
                        type: 'line',
                        options: {
                            responsive: true,
                            animation: false,
                            plugins: {
                                htmlLegend: {
                                    containerID: '<?= $chartId ?>-legend-container',
                                },
                                legend: {
                                    display: <?= $show_legend ? 'true' : 'false' ?>,
                                },
                                tooltip: {
                                    enabled: true,
                                    usePointStyle: true,
                                    callbacks: {
                                        title: (data) => data[0].dataset.label,
                                        label: (data) => <?= $_block->getTooltipJsCallback() ?>,
                                    },
                                },
                            },
                            scales: {
                                x: {
                                    type: 'time',
                                    time: {
                                        unit: 'week',
                                        isoWeekday: true,
                                    }
                                },
                            }
                        },
                        <?php if ($show_legend): ?>
                        plugins: [whbChartjs.htmlLegendPlugin],
                        <?php endif; ?>
                    });

                    const updateChart = function() {
                        var filters = $('#<?= $chartId ?>_form').serialize();
                        $.getJSON("<?= $data_url ?>", filters, function(data) {
                            $('#<?= $chartId ?> .no-data-message').remove();
                            if (data == null || !data.datasets?.length) {
                                if (typeof chart != "undefined") {
                                    chart.clear();
                                }
                                $('#<?= $chartId ?> canvas').after('<div class="no-data-message"><?= $this->__($no_data_message); ?></div>');
                                return;
                            } else {
                                whbChartjs.populateLineChartWithData(chart, data);
                            }
                        });
                    }

                    $(window).load(function() {
                        updateChart();
                        $('#<?= $chartId ?> .toolbar select').change(updateChart);
                    });
                })(jQuery);
            });
            //]]>
        </script>
        <div class="clear"></div>
        <?php if ($footer_note): ?>
            <div class="chart-footer right">
                <p><?= $footer_note ?></p>
            </div>
        <?php endif; ?>
    </div>
</div>
