<?php
/**
 * Created by PhpStorm.
 * User: anael
 * Date: 11/11/15
 * Time: 14:35
 */
/* @var $this \app\models\core\View */

$chartId = $id;
$chartVar = 'chart_' . $chartId . '_';
?>

<div id="<?php echo $chartId ?>" class="chart <?php echo $class ?> <?php echo $type ?>">
    <div class="chart-heading">
        <h2 class="chart-title"><?php echo $this->__($title) ?></h2>
    </div>
    <div class="chart-body">
        <div class="toolbar">
            <form action="javascript:void(0)" id="<?php echo $chartId ?>_form">
                <ul>
                    <?php foreach ($filters as $filterElement): /* @var $filterElement \app\models\core\Form\Element\AbstractElement */ ?>
                        <li>
                            <span class="filter-label"><?php echo $this->__($filterElement->getLabel()) ?></span>
                            <div class="filter-input">
                                <?php echo $filterElement->toHtml() ?>
                            </div>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </form>
        </div>
        <?php if ($show_legend): ?>
            <div class="legend"></div>
        <?php endif; ?>

        <div class="canvas-container">
            <div class="loading-anim"></div>
            <canvas width="<?php echo $width ?>" height="<?php echo $height ?>"></canvas>
        </div>

        <script type="application/javascript">
            //<![CDATA[
            var <?php echo $chartVar ?>Canvas;
            var <?php echo $chartVar ?>;
            function update<?php echo $chartVar ?>Chart() {
                $('#<?php echo $chartId ?> .loading-anim').show();

                var filters = $('#<?php echo $chartId ?>_form').serialize();
                if (typeof(<?php echo $chartVar ?>) != "undefined") {
                    <?php echo $chartVar ?>.destroy();
                }
                <?php echo $chartVar ?>Canvas = new Chart($('#<?php echo $chartId ?> canvas').get(0).getContext('2d'));
                $.getJSON("<?php echo $data_url ?>", filters, function(data) {
                    $('#<?php echo $chartId ?> .loading-anim').hide();
                    $('#<?php echo $chartId ?> .no-data-message').remove();
                    if (data == null || data.datasets.length == 0) {
                        if (typeof <?php echo $chartVar ?> != "undefined") {
                            <?php echo $chartVar ?>.clear();
                        }
                        $('#<?php echo $chartId ?> canvas').after('<div class="no-data-message"><?php echo $this->__($no_data_message); ?></div>');
                        return;
                    }
                    for (var i in data['datasets']) {
                        for (var j in data['datasets'][i]['data']) {
                            var ts = data['datasets'][i]['data'][j]['x'] * 1000;
                            data['datasets'][i]['data'][j]['x'] = new Date(ts);
                        }
                    }
                    <?php echo $chartVar ?> = <?php echo $chartVar ?>Canvas.Scatter(data, {
                        animation: false,
                        responsive: true,
                        scaleType: 'date',
                        scaleBeginAtZero: true,
                        datasetFill: false,
                        pointHitDetectionRadius: 3,
                        <?php if ($empty_data_message): ?>
                            emptyDataMessage: '<?php echo \app\helpers\core\Output::jsQuoteEscape($empty_data_message) ?>',
                        <?php endif ?>
                        <?php if ($scale_date_time_format): ?>
                            scaleDateTimeFormat: '<?php echo \app\helpers\core\Output::jsQuoteEscape($scale_date_time_format) ?>',
                        <?php endif ?>
                        <?php if ($scale_date_format): ?>
                            scaleDateFormat: '<?php echo \app\helpers\core\Output::jsQuoteEscape($scale_date_format) ?>',
                        <?php endif ?>
                        <?php if ($scale_label): ?>
                            scaleLabel: '<?php echo \app\helpers\core\Output::jsQuoteEscape($scale_label) ?>',
                        <?php endif ?>
                        <?php if ($scale_arg_label): ?>
                            scaleArgLabel: '<?php echo \app\helpers\core\Output::jsQuoteEscape($scale_arg_label) ?>',
                        <?php endif ?>
                        <?php if ($legend_template): ?>
                            legendTemplate: '<?php echo \app\helpers\core\Output::jsQuoteEscape($legend_template) ?>',
                        <?php endif ?>
                        <?php if ($tooltip_template): ?>
                            tooltipTemplate: '<?php echo \app\helpers\core\Output::jsQuoteEscape($tooltip_template) ?>',
                        <?php endif ?>
                        <?php if ($multi_tooltip_template): ?>
                            multiTooltipTemplate: '<?php echo \app\helpers\core\Output::jsQuoteEscape($multi_tooltip_template) ?>'
                        <?php endif ?>
                    });
                    $('#<?php echo $chartId ?> .legend').empty();
                    try {
                        $('#<?php echo $chartId ?> .legend').append(<?php echo $chartVar ?>.generateLegend());
                    }
                    catch (e) {
                        // just ignore
                    }
                });
            }

            $(window).load(function() {
                update<?php echo $chartVar ?>Chart();
                $('#<?php echo $chartId ?> .toolbar select').change(update<?php echo $chartVar ?>Chart);
            });
            //]]>
        </script>
        <div class="clear"></div>
        <?php if ($footer_note): ?>
            <div class="chart-footer right">
                <p><?php echo $footer_note ?></p>
            </div>
        <?php endif; ?>
    </div>
</div>