variables:
  CONTAINER_RELEASE_IMAGE: "nanawel/webhomebank"
  BUILD_IMAGE: "webhomebank"

stages:
  - check
  - build
  - release

before_script:
  - time docker info
  - time docker login ${REGISTRY_SERVER}
  - export WEBAPP_VERSION=${CI_COMMIT_TAG:-dev}
  - env

build_image:
  stage: build
  script:
    - time docker build -t ${BUILD_IMAGE} --build-arg appVersion=${WEBAPP_VERSION} .
    - time docker tag ${BUILD_IMAGE}:latest ${CONTAINER_RELEASE_IMAGE}:${CI_COMMIT_SHORT_SHA}
    - time docker push ${CONTAINER_RELEASE_IMAGE}:${CI_COMMIT_SHORT_SHA}
  tags:
    - shell
    - docker

push_image_latest:
  stage: release
  script:
    - time docker pull ${CONTAINER_RELEASE_IMAGE}:${CI_COMMIT_SHORT_SHA}
    - time docker tag ${CONTAINER_RELEASE_IMAGE}:${CI_COMMIT_SHORT_SHA} ${CONTAINER_RELEASE_IMAGE}:latest
    - time docker push ${CONTAINER_RELEASE_IMAGE}:latest
  tags:
    - shell
    - docker
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'

push_image_tagged:
  stage: release
  script:
    - time docker pull ${CONTAINER_RELEASE_IMAGE}:${CI_COMMIT_SHORT_SHA}
    - time docker tag ${CONTAINER_RELEASE_IMAGE}:${CI_COMMIT_SHORT_SHA} ${CONTAINER_RELEASE_IMAGE}:${CI_COMMIT_REF_SLUG}
    - time docker push ${CONTAINER_RELEASE_IMAGE}:${CI_COMMIT_REF_SLUG}
  tags:
    - shell
    - docker
  rules:
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/'
