services:
  app:
    image: ${DOCKER_IMAGE:-nanawel/webhomebank}
    build:
      context: './'
    restart: unless-stopped
    ports:
      - '${HOST_PORT:-49080}:80'
    volumes:
      - ${DATA_DIR}:/data:ro
    deploy:
      resources:
        limits:
          # This is the minimum recommended, otherwise XHB loading might silently fail
          # and the message "UNIQUE constraint failed (...)" would show up on the loading screen
          memory: 256M
