<?php
/* @var $this \app\models\whb\View */
$fw = \Base::instance();
$design = \app\models\core\Design::instance();
$url = \app\models\core\Url::instance();

?>
<div class="contain-to-grid sticky">
    <nav class="nav-container top-bar" data-topbar role="navigation">
        <ul class="brand title-area">
            <li class="home-link name">
                <a href="<?= $this->getUrl('/') ?>">
                    <img class="logo" src="<?= $design->getImageUrl('logo.png') ?>" alt="<?= $fw->get('app.TITLE') ?> logo" height="60"/>
                </a>
                <h1><a href="<?= $this->getUrl('/') ?>"><?= $fw->get('app.TITLE') ?></a></h1>
            </li>
            <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
        </ul>
        <?= $this->renderBlock('header.nav'); ?>
    </nav>
</div>
