<?php
/* @var $this \app\models\whb\View */
$fw = \Base::instance();
$design = \app\models\core\Design::instance();
$url = \app\models\core\Url::instance();

?>
<div class="title-bar" data-responsive-toggle="responsive-menu" data-hide-for="medium">
    <button class="menu-icon" type="button" data-toggle="responsive-menu"></button>
    <div class="title-bar-title">Menu</div>

    <div class="logo-container">
        <a href="<?= $this->getUrl('/') ?>">
            <img class="logo" src="<?= $design->getImageUrl('logo.png') ?>" alt="<?= $fw->get('app.TITLE') ?> logo" height="60">
            <?= $fw->get('app.TITLE') ?>
        </a>
    </div>
</div>

<div class="top-bar" id="responsive-menu">
    <div class="top-bar-left show-for-medium">
        <ul class="dropdown menu" data-dropdown-menu>
            <li class="menu-text">
                <a href="<?= $this->getUrl('/') ?>">
                    <img class="logo" src="<?= $design->getImageUrl('logo.png') ?>" alt="<?= $fw->get('app.TITLE') ?> logo" height="60">
                    <?= $fw->get('app.TITLE') ?>
                </a>
            </li>
        </ul>
    </div>
    <?= $this->renderBlock('header.nav'); ?>
</div>
