<?php
/* @var $this \app\models\core\View */
$fw = \Base::instance();
$requestCacheIndicator = $this->isRenderingPlaceholders() ? '<sup>*</sup>' : '';
?>
<p><?= $this->__('Page rendered in {0} msecs{2} / Memory usage {1} Kibytes', round(1e3*(microtime(TRUE)-$fw->get('TIME')),2), round(memory_get_usage(TRUE)/1e3,1), $requestCacheIndicator); ?></p>
<p><?= $this->__('{0} {1} - Powered by {2} {3}', $fw->get('app.TITLE'), $fw->get('app.VERSION'), $fw->get('PACKAGE'), $fw->get('VERSION')) ?></p>
