<?php
/* @var $this \app\models\whb\View */
$fw = \Base::instance();
$design = \app\models\core\Design::instance();
$url = \app\models\core\Url::instance();
?>
<div class="header">
    <div class="nav-container">
        <div class="brand">
            <div class="home-link">
                <a href="<?= $this->getUrl('/') ?>">
                    <img class="logo" src="<?= $design->getImageUrl('logo.png') ?>" alt="<?= $fw->get('app.TITLE') ?> logo" height="60">
                </a>
                <h1><a href="<?= $this->getUrl('/') ?>"><?= $fw->get('app.TITLE') ?></a></h1>
            </div>
        </div>
        <div class="separator"></div>
        <?= $this->renderBlock('header.nav'); ?>
    </div>
</div>
