<?php
$fw = \Base::instance();
$design = \app\models\core\Design::instance();
$url = \app\models\core\Url::instance();
?>
<head>
    <meta charset="<?= $fw->get('ENCODING'); ?>" />
    <title><?= $fw->get('PAGE_TITLE') ?></title>
    <base href="<?= $url->getBaseUrl(); ?>" />
    <?php if ($faviconUrl = $design->getFaviconUrl()): ?>
        <link rel="icon" type="image/png" href="<?= $faviconUrl ?>" />
    <?php endif; ?>

    <?= $design->renderItems('header'); ?>
</head>
