<?php
/* @var $this \app\models\whb\View */
$fw = \Base::instance();
$design = \app\models\core\Design::instance();
$url = \app\models\core\Url::instance();
?>
<div class="header">
    <div class="nav-container">
        <div class="brand">
            <div class="home-link">
                <a href="<?php echo $this->getUrl('/') ?>">
                    <img class="logo" src="<?php echo $design->getImageUrl('logo.png') ?>" alt="<?php echo $fw->get('app.TITLE') ?> logo" height="60"/>
                </a>
                <h1><a href="<?php echo $this->getUrl('/') ?>"><?php echo $fw->get('app.TITLE') ?></a></h1>
            </div>
        </div>
        <div class="separator"></div>
        <?php echo $this->renderBlock('header.nav'); ?>
    </div>
</div>