<!DOCTYPE html>
<?php
$fw = \Base::instance();
$design = \app\models\core\Design::instance();
$url = \app\models\core\Url::instance();
/* @var $this \app\models\core\View */
?>
<html lang="<?= $fw->get('HTML_LANG'); ?>">

    <?= $this->renderBlock('head') ?>

    <body<?php if ($class = $design->getBodyClass()) echo ' class="' . $class . ' no-js"' ?>>

        <div class="header-container">
            <?= $this->renderBlock('header') ?>
        </div>

        <div class="clear"></div>

        <div class="main-content">
            <div class="session-messages">
                <?= $this->renderBlock('messages'); ?>
            </div>
            <div id="content-wrapper">
                <div class="content">
                    <?= $this->renderBlock('content'); ?>
                </div>
            </div>
        </div>

        <div class="clear"></div>
        <div class="footer center">
            <?= $this->renderBlock('footer') ?>
        </div>

        <?= $design->renderItems('footer'); ?>
    </body>
</html>
