<?php
/* @var $this \app\models\whb\View */
$fw = \Base::instance();
$design = \app\models\core\Design::instance();
$url = \app\models\core\Url::instance();
$session = $this->getSession();
$i18n = \app\models\core\I18n::instance();
?>

<div class="top-bar-right">
    <ul class="vertical medium-horizontal menu" data-responsive-menu="drilldown medium-dropdown">
        <li class="account-operations-links has-submenu">
            <a href="javascript:"><?= $this->__('Account Operations') ?></a>
            <ul class="submenu menu vertical" data-submenu>
                <?php foreach($this->getModel()->getAccountCollection() as $account): ?>
                    <li class="level-2 account-operations-link">
                        <a href="<?= $url->getUrl('account_operation/index', array('account_id' => $account->getId())) ?>"><?= $account->getName() ?></a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </li>
        <li class="vehiclecost-link">
            <a href="<?= $url->getUrl('report_vehiclecost/index') ?>"><?= $this->__('Vehicle Cost') ?></a>
        </li>
        <li class="settings-links has-submenu">
            <a href="javascript:"><?= $this->__('Settings') ?></a>
            <ul class="submenu menu vertical" data-submenu>
                <li class="has-submenu settings-currency-links">
                    <a href="javascript:"><?= $this->__('Currency') ?></a>
                    <ul class="submenu menu vertical">
                        <?php foreach($i18n->getAvailableCurrencies() as $code): ?>
                            <li class="set-currency-link currency-<?= strtolower($code) ?>">
                                <a href="<?= $url->getUrl('settings/setCurrency', array('_query' => array('code' => $code))) ?>"><?= $code ?></a>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </li>
                <li class="has-submenu settings-locale-links">
                    <a href="javascript:"><?= $this->__('Locale') ?></a>
                    <ul class="submenu menu vertical">
                        <?php foreach($i18n->getAvailableLocales() as $code): ?>
                            <li class="set-locale-link currency-<?= strtolower($code) ?>">
                                <a href="<?= $url->getUrl('settings/setLocale', array('_query' => array('code' => $code))) ?>"><?= $code ?></a>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </li>
                <li class="has-submenu settings-theme-links">
                    <a href="javascript:"><?= $this->__('Theme') ?></a>
                    <ul class="submenu menu vertical">
                        <?php foreach($design->getAvailableThemes() as $code): ?>
                            <li class="set-theme-link theme-<?= strtolower($code) ?>">
                                <a href="<?= $url->getUrl('settings/setTheme', array('_query' => array('code' => $code))) ?>"><?= $code ?></a>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </li>
            </ul>
        </li>
    </ul>
</div>
