<?php
/* @var $this \app\models\whb\View */
$fw = \Base::instance();
$design = \app\models\core\Design::instance();
$url = \app\models\core\Url::instance();
$session = $this->getSession();
$i18n = \app\models\core\I18n::instance();
?>
<section class="top-bar-section">
    <ul class="nav-menu right" id="nav">
        <li class="level-1 account-operations-links has-dropdown">
            <a href="javascript:void(0)"><?php echo $this->__('Account Operations') ?></a>
            <ul class="dropdown">
                <?php foreach($this->getModel()->getAccountCollection() as $account): ?>
                    <li class="level-2 account-operations-link">
                        <a href="<?php echo $url->getUrl('account_operation/index', array('account_id' => $account->getId())) ?>"><?php echo $account->getName() ?></a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </li>
        <li class="level-1 vehiclecost-link">
            <a href="<?php echo $url->getUrl('report_vehiclecost/index') ?>"><?php echo $this->__('Vehicle Cost') ?></a>
        </li>

        <li class="level-1 settings-links has-dropdown">
            <a href="javascript:void(0)"><?php echo $this->__('Settings') ?></a>
            <ul class="dropdown">
                <li class="level-2 settings-currency-links has-dropdown">
                    <a href="javascript:void(0)"><?php echo $this->__('Currency') ?></a>
                    <ul class="dropdown">
                        <?php foreach($i18n->getAvailableCurrencies() as $code): ?>
                            <li class="level-3 set-currency-link currency-<?php echo strtolower($code) ?>">
                                <a href="<?php echo $url->getUrl('settings/setCurrency', array('_query' => array('code' => $code))) ?>"><?php echo $code ?></a>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </li>
                <li class="level-2 settings-locale-links has-dropdown">
                    <a href="javascript:void(0)"><?php echo $this->__('Locale') ?></a>
                    <ul class="dropdown">
                        <?php foreach($i18n->getAvailableLocales() as $code): ?>
                            <li class="level-3 set-locale-link currency-<?php echo strtolower($code) ?>">
                                <a href="<?php echo $url->getUrl('settings/setLocale', array('_query' => array('code' => $code))) ?>"><?php echo $code ?></a>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </li>
                <li class="level-2 settings-theme-links has-dropdown">
                    <a href="javascript:void(0)"><?php echo $this->__('Theme') ?></a>
                    <ul class="dropdown">
                        <?php foreach($design->getAvailableThemes() as $code): ?>
                            <li class="level-3 set-theme-link theme-<?php echo strtolower($code) ?>">
                                <a href="<?php echo $url->getUrl('settings/setTheme', array('_query' => array('code' => $code))) ?>"><?php echo $code ?></a>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </li>
            </ul>
        </li>
    </ul>
</section>
