<?php
/* @var $this \app\models\whb\View */
$account = \Base::instance()->get('current_account');
$noResults = count($OPERATION_COLLECTION) == 0;
$gridHelper = \app\models\core\Grid::instance();
$now = new \DateTime();
?>

<div class="back-link top">
    <span><a href="<?= $this->getUrl('account') ?>"><?= $this->__('Back to accounts page') ?></a></span>
</div>

<h1><?= $account->getName() ?></h1>
<div class="account-summary">
    <?= $this->renderBlock('account_summary'); ?>
</div>

<div class="clear"></div>

<?= $this->renderBlock('operation_toolbar'); ?>

<div id="total-balance"><?= $this->__('{0} item(s) ({1})', count($OPERATION_COLLECTION), $this->i18n()->currency($OPERATION_COLLECTION->getBalance(), true)) ?></div>
<table class="data-table operations-table<?php if ($noResults): echo ' no-data'; endif; ?>">
    <thead>
        <tr>
            <th><a href="<?= $gridHelper->getOrderLinkUrl($CURRENT_ORDER, array('date' => null)) ?>"><?= $this->__('Date') ?></a></th>
            <th><a href="<?= $gridHelper->getOrderLinkUrl($CURRENT_ORDER, array('info' => null)) ?>"><?= $this->__('Info') ?></a></th>
            <th><a href="<?= $gridHelper->getOrderLinkUrl($CURRENT_ORDER, array('payee' => null)) ?>"><?= $this->__('Payee') ?></a></th>
            <th><a href="<?= $gridHelper->getOrderLinkUrl($CURRENT_ORDER, array('category' => null)) ?>"><?= $this->__('Category') ?></a></th>
            <th><?= $this->__('Tags') ?></th>
            <th><a href="<?= $gridHelper->getOrderLinkUrl($CURRENT_ORDER, array('status' => null)) ?>"><?= $this->__('Status') ?></a></th>
            <th><a href="<?= $gridHelper->getOrderLinkUrl($CURRENT_ORDER, array('amount' => null)) ?>"><?= $this->__('Outcome') ?></a></th>
            <th><a href="<?= $gridHelper->getOrderLinkUrl($CURRENT_ORDER, array('amount' => null)) ?>"><?= $this->__('Income') ?></a></th>
            <th><?= $this->__('Balance') ?></th>
            <th><a href="<?= $gridHelper->getOrderLinkUrl($CURRENT_ORDER, array('wording' => null)) ?>"><?= $this->__('Memo') ?></a></th>
        </tr>
    </thead>
    <tbody>
        <?php if ($noResults): ?>
        <tr class="operation">
            <td colspan="10"><?= $this->__('No data for this period of time') ?></td>
        </tr>
        <?php else: ?>
            <?php foreach($OPERATION_COLLECTION as $operation): /* @var $operation \Xhb\Model\Operation */?>
            <?php
                $outcome = $operation->getAmount() < 0 ? $this->i18n()->currency($operation->getAmount(), true) : '';
                $income = $operation->getAmount() >= 0 ? $this->i18n()->currency($operation->getAmount(), true) : '';
                $balance = $this->i18n()->currency($operation->getAccountBalance(), true);
                $category = $operation->getCategoryModels();
                if (!empty($category)) {
                    $categoryName = count($category) == 1 ? $category[0]->getFullname() : $this->__('- split -');
                }
                else {
                    $categoryName = false;
                }
            ?>
            <tr class="operation<?php if ($paymode = $operation->getPaymodeCode()) echo ' paymode-' . $paymode; ?><?php if ($operation->getDateModel() > $now) echo ' future'; ?>">
                <td class="date"><?= $this->i18n()->date($operation->getDateModel()) ?></td>
                <td class="info"><?= $operation->getInfo() ?></td>
                <td class="payee"><?= \app\helpers\whb\AccountOperation::getPayeeLabelForDisplay($operation) ?></td>
                <td class="category"><?= $categoryName ? $categoryName : '&nbsp;' ?></td>
                <td class="tags"><?= $operation->getTags() ?></td>
                <td class="status"><span class="status-icon status-<?= $operation->getStatus() ?>"></span></td>
                <td class="currency outcome"><?= $outcome ?></td>
                <td class="currency income"><?= $income ?></td>
                <td class="currency balance"><?= $balance ?></td>
                <td class="memo"><?= $operation->getWording() ?></td>
            </tr>
            <?php endforeach; ?>
        <?php endif; ?>
    </tbody>
</table>

<div class="clear"></div>
<div class="charts-container">
    <?= $this->renderBlock('charts'); ?>
</div>

<div class="clear"></div>
<div class="back-link bottom">
    <span><a href="<?= $this->getUrl('account') ?>"><?= $this->__('Back to accounts page') ?></a></span>
</div>
