<div class="toolbar">
    <?php if (isset($FILTER_FORM_ACTION) && $FILTER_FORM_ACTION && isset($FILTERS) && !empty($FILTERS)): ?>
        <form action="<?= $FILTER_FORM_ACTION ?>" method="get" target="_self" id="toolbar-form">
            <ul>
                <?php foreach ($FILTERS as $filterElement): /* @var $filterElement \app\models\core\Form\Element\AbstractElement */ ?>
                    <?php if ($filterElement->getName() == 'search') continue; ?>
                    <li class="filter-container">
                        <label for="<?= $filterElement->getId() ?>" class="filter-label"><?= $this->__($filterElement->getLabel()) ?></label>
                        <?= $filterElement->toHtml() ?>
                    </li>
                <?php endforeach; ?>
                <li class="buttons-set">
                    <button class="hidden" type="submit"><?= $this->__('Submit') ?></button>
                    <button class="reset"><?= $this->__('Reset') ?></button>
                </li>
                <?php if (isset($FILTERS['search'])): ?>
                    <li class="filter-container">
                        <?= $FILTERS['search']->toHtml() ?>
                    </li>
                <?php endif; ?>
            </ul>
        </form>
        <script>
            window.addEventListener('DOMContentLoaded', function() {
                (function($) {
                    $('#toolbar-form select').change(function() {
                        $('#toolbar-form').submit();
                    });
                    $('#toolbar-form button.reset').click(function(ev) {
                        window.location = "<?= $RESET_FILTERS_URL ?>";
                        return false;
                    });
                })(jQuery);
            });
        </script>
    <?php endif; ?>
</div>

