<div class="toolbar">
    <?php if (!empty($FILTER_FORM_ACTION) && !empty($FILTERS)): ?>
        <form action="<?= $FILTER_FORM_ACTION ?>" method="get" target="_self" id="toolbar-form">
            <ul>
                <?php foreach ($FILTERS as $filterElement): /* @var $filterElement \app\models\core\Form\Element\AbstractElement */ ?>
                    <?php if ($filterElement->getName() == 'search') continue; ?>
                    <li class="filter-container">
                        <div class="input-group">
                            <span class="input-group-label"><?= $this->__($filterElement->getLabel()) ?></span>
                            <?= $filterElement->addClass('input-group-field')->toHtml() ?>
                        </div>
                    </li>
                <?php endforeach; ?>
                <li class="buttons-set">
                    <button class="hidden" type="submit"><?= $this->__('Submit') ?></button>
                    <button class="reset"><?= $this->__('Reset') ?></button>
                </li>
                <?php if (isset($FILTERS['search'])): ?>
                    <li class="filter-container">
                        <?= $FILTERS['search']->toHtml() ?>
                    </li>
                <?php endif; ?>
            </ul>
        </form>
        <script>
            window.addEventListener('DOMContentLoaded', function() {
                (function($) {
                    $('#toolbar-form select').change(function() {
                        $('#toolbar-form').submit();
                    });
                    $('#toolbar-form button.reset').click(function(ev) {
                        window.location = "<?= $RESET_FILTERS_URL ?>";
                        return false;
                    });
                })(jQuery);
            });
        </script>
    <?php endif; ?>
</div>

