<?php
/* @var $this \app\models\whb\View */
$fw = \Base::instance();
$design = \app\models\core\Design::instance();
$url = \app\models\core\Url::instance();
$session = $this->getSession();
$i18n = \app\models\core\I18n::instance();
?>
<ul class="nav-menu dropdown dropdown-horizontal" id="nav">
    <li class="level-1 account-operations-links dir">
        <?php echo $this->__('Account Operations') ?>
        <ul class="dir">
            <?php foreach($this->getModel()->getAccountCollection() as $account): ?>
                <li class="level-2 account-operations-link">
                    <a href="<?php echo $url->getUrl('account_operation/index', array('account_id' => $account->getId())) ?>"><?php echo $account->getName() ?></a>
                </li>
            <?php endforeach; ?>
        </ul>
    </li>
    <li class="level-1 vehiclecost-link">
        <a href="<?php echo $url->getUrl('report_vehiclecost/index') ?>"><?php echo $this->__('Vehicle Cost') ?></a>
    </li>
    <li class="level-1 settings-link dir">
        <?php echo $this->__('Settings') ?>
        <ul class="dir">
            <li class="level-2 settings-currency-link dir">
                <ul class="dir">
                    <?php foreach($i18n->getAvailableCurrencies() as $code): ?>
                        <li class="level-3 set-currency-link currency-<?php echo strtolower($code) ?>">
                            <a href="<?php echo $url->getUrl('settings/setCurrency', array('_query' => array('code' => $code))) ?>"><?php echo $code ?></a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </li>
            <li class="level-2 settings-locale-link dir">
                <ul class="dir">
                    <?php foreach($i18n->getAvailableLocales() as $code): ?>
                        <li class="level-3 set-locale-link currency-<?php echo strtolower($code) ?>">
                            <a href="<?php echo $url->getUrl('settings/setLocale', array('_query' => array('code' => $code))) ?>"><?php echo $code ?></a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </li>
        </ul>
    </li>
</ul>