<?php
/* @var $this \app\models\whb\View */
$fw = \Base::instance();
$design = \app\models\core\Design::instance();
$url = \app\models\core\Url::instance();
?>
<ul class="nav-menu dropdown dropdown-horizontal" id="nav">
    <li class="level-1 account-operations-links dir">
        <?php echo $this->__('Account Operations') ?>
        <ul class="dir">
            <?php foreach($this->getModel()->getAccountCollection() as $account): ?>
                <li class="level-2 account-operations-link">
                    <a href="<?php echo $url->getUrl('account_operation/index', array('account_id' => $account->getId())) ?>"><?php echo $account->getName() ?></a>
                </li>
            <?php endforeach; ?>
        </ul>
    </li>
    <li class="level-1 vehiclecost-link">
        <a href="<?php echo $url->getUrl('report_vehiclecost/index') ?>"><?php echo $this->__('Vehicle Cost') ?></a>
    </li>
</ul>