<?php
/* @var $this \app\models\whb\View */
$fw = \Base::instance();
$design = \app\models\core\Design::instance();
$url = \app\models\core\Url::instance();
$session = $this->getSession();
$i18n = \app\models\core\I18n::instance();
?>
<ul class="nav-menu dropdown dropdown-horizontal" id="nav">
    <li class="level-1 account-operations-links dir">
        <?= $this->__('Account Operations') ?>
        <ul class="dir">
            <?php foreach($this->getModel()->getAccountCollection() as $account): ?>
                <?php if ($account->getFlags() & \Xhb\Model\Constants::ACC_FLAG_NOSUMMARY) continue; ?>
                <li class="level-2 account-operations-link">
                    <a href="<?= $url->getUrl('account_operation/index', array('account_id' => $account->getId())) ?>"><?= $account->getName() ?></a>
                </li>
            <?php endforeach; ?>
        </ul>
    </li>
    <li class="level-1 vehiclecost-link">
        <a href="<?= $url->getUrl('report_vehiclecost/index') ?>"><?= $this->__('Vehicle Cost') ?></a>
    </li>
    <li class="level-1 settings-links dir">
        <?= $this->__('Settings') ?>
        <ul class="dir">
            <li class="level-2 settings-currency-link dir">
                <?= $this->__('Currency') ?>
                <ul class="dir">
                    <?php foreach($i18n->getAvailableCurrencies() as $code): ?>
                        <li class="level-3 set-currency-link currency-<?= strtolower($code) ?>">
                            <a href="<?= $url->getUrl('settings/setCurrency', array('_query' => array('code' => $code))) ?>"><?= $code ?></a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </li>
            <li class="level-2 settings-locale-link dir">
                <?= $this->__('Locale') ?>
                <ul class="dir">
                    <?php foreach($i18n->getAvailableLocales() as $code): ?>
                        <li class="level-3 set-locale-link currency-<?= strtolower($code) ?>">
                            <a href="<?= $url->getUrl('settings/setLocale', array('_query' => array('code' => $code))) ?>"><?= $code ?></a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </li>
            <li class="level-2 settings-theme-link dir">
                <?= $this->__('Theme') ?>
                <ul class="dir">
                    <?php foreach($design->getAvailableThemes() as $code): ?>
                        <li class="level-3 set-theme-link theme-<?= strtolower($code) ?>">
                            <a href="<?= $url->getUrl('settings/setTheme', array('_query' => array('code' => $code))) ?>"><?= $code ?></a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </li>
        </ul>
    </li>
</ul>
