<?php
/* @var $account \Xhb\Model\Account */
$account = \Base::instance()->get('current_account');
?>
<div class="account-balance-summary">
    <div class="label-value-group">
        <label class="label first"><?= $this->__('Bank: ') ?></label>
        <span class="value balance bank-balance"><?= $this->i18n()->currency($account->getBankBalance(), true) ?></span>
    </div>
    <div class="label-value-group">
        <label class="label"><?= $this->__('Today: ') ?></label>
        <span class="value balance today-balance"><?= $this->i18n()->currency($account->getTodayBalance(), true) ?></span>
    </div>
    <div class="label-value-group">
        <label class="label"><?= $this->__('Future: ') ?></label>
        <span class="value balance future-balance last"><?= $this->i18n()->currency($account->getFutureBalance(), true) ?></span>
    </div>
</div>

